name: 'download-bitrise-yaml'
description: 'A GitHub Action for downloading bitrise.yml'
author: 'IKEDA Sho'
inputs:
  appSlug:
    description: 'Btirise app slug'
  outputPath:
    description: 'A path where the downloaded file is saved'
    default: 'bitrise.yml'
  bitriseToken:
    description: 'Bitrise personal access token'
runs:
  using: 'node12'
  main: 'dist/index.js'
