name: 'Download bitrise.yml'
description: 'GitHub Action for downloading bitrise.yml'
author: 'IKEDA Sho'
inputs:
  app_slug:
    description: 'Btirise app slug'
  output_path:
    description: 'A path where the downloaded file is saved'
    default: 'bitrise.yml'
  bitrise_token:
    description: 'Bitrise personal access token'
runs:
  using: 'node12'
  main: 'dist/index.js'
